# This build file has been generated by c_build
if ($PSVersionTable.Platform -eq "Unix") {
    Set-Alias python python3
}

$directoryPath = "./c_build"
$repositoryUrl = "https://github.com/superg3m/c_build.git"

if (-not (Test-Path -Path $directoryPath)) {
    Write-Output "Directory does not exist. Cloning the repository..."
    git clone $repositoryUrl
} else {
    Push-Location  "./c_build"
    git fetch origin -q
    git reset --hard origin/main -q
    git pull -q
    Pop-Location
}

. ./c_build/validate_temp_files.ps1 $MyInvocation.MyCommand.Name

$bootstrapScriptPath = "$directoryPath/bootstrap.ps1"
if (Test-Path -Path $bootstrapScriptPath) {
    & $bootstrapScriptPath
} else {
    Write-Output "Bootstrap script not found at $bootstrapScriptPath"
}
