#!/bin/bash

# This build file has been generated by c_build

# Ensure `python` points to `python3` on Unix systems
if [[ "$(uname)" != "Windows_NT" ]]; then
    alias python=python3
fi

directoryPath="./c_build"
repositoryUrl="https://github.com/superg3m/c_build.git"

if [ ! -d "$directoryPath" ]; then
    echo "Directory does not exist. Cloning the repository..."
    git clone "$repositoryUrl"
else
    pushd "./c_build" > /dev/null
    git fetch origin -q
    git reset --hard origin/main -q
    git pull -q
    popd > /dev/null
fi

# Source the validation script
if [ -f "./c_build/validate_temp_files.sh" ]; then
    bash "./c_build/validate_temp_files.sh" "$(basename "$0")"
else
    echo "Validation script not found."
fi

bootstrapScriptPath="$directoryPath/bootstrap.sh"
if [ -f "$bootstrapScriptPath" ]; then
    bash "$bootstrapScriptPath"
else
    echo "Bootstrap script not found at $bootstrapScriptPath"
fi

