# This build file has been generated by C-Build

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $true

Push-Location  "./c-build"
git fetch origin
git reset --hard origin/main
git pull
Pop-Location

./c-build/cl/clean.ps1

# ok clean is not quiet right anymore you need to clean all build_procedures
