# This build file has been generated by C-Build
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $true

Push-Location  ".\C-BUILD"
git stash
git stash drop
git pull
Pop-Location

./C-BUILD/cl/clean.ps1

# ok clean is not quiet right anymore you need to clean all build_procedures
